/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation */

#ifndef _Included_org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation
#define _Included_org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation
 * Method:    evaluateAdd
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation_evaluateAdd
  (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT jstring JNICALL Java_org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation_evaluateSubtract
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
