/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wso2_siddhi_extension_he_api_HomomorphicEncDecService */

#ifndef _Included_org_wso2_siddhi_extension_he_api_HomomorphicEncDecService
#define _Included_org_wso2_siddhi_extension_he_api_HomomorphicEncDecService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wso2_siddhi_extension_he_api_HomomorphicEncDecService
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wso2_siddhi_extension_he_api_HomomorphicEncDecService_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wso2_siddhi_extension_he_api_HomomorphicEncDecService
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wso2_siddhi_extension_he_api_HomomorphicEncDecService_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_wso2_siddhi_extension_he_api_HomomorphicEncDecService
 * Method:    generateKeys
 * Signature: (Ljava/lang/String;JJJJJJJJ)V
 */
JNIEXPORT void JNICALL Java_org_wso2_siddhi_extension_he_api_HomomorphicEncDecService_generateKeys
  (JNIEnv *, jobject, jstring, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_wso2_siddhi_extension_he_api_HomomorphicEncDecService
 * Method:    encryptLong
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wso2_siddhi_extension_he_api_HomomorphicEncDecService_encryptLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wso2_siddhi_extension_he_api_HomomorphicEncDecService
 * Method:    decryptLong
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_wso2_siddhi_extension_he_api_HomomorphicEncDecService_decryptLong
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wso2_siddhi_extension_he_api_HomomorphicEncDecService
 * Method:    encryptLong
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wso2_siddhi_extension_he_api_HomomorphicEncDecService_encryptLongVector
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_wso2_siddhi_extension_he_api_HomomorphicEncDecService
 * Method:    decryptLong
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jstring JNICALL Java_org_wso2_siddhi_extension_he_api_HomomorphicEncDecService_decryptLongVector
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
